import { NextRequest, NextResponse } from 'next/server';
import { createServerSupabase } from '@/lib/supabase/server';
import { getUserTokens } from '@/lib/deploy/getTokens';
import { createGitHubRepo, pushFilesToRepo } from '@/lib/deploy/github';
import { createSupabaseProject, executeSqlOnProject } from '@/lib/deploy/supabase';
import { deployToNetlify } from '@/lib/deploy/netlify';
import { deployToVercel } from '@/lib/deploy/vercel';
import { deployToCloudflare } from '@/lib/deploy/cloudflare';

export async function POST(request: NextRequest, { params }: { params: { id: string } }) {
  const supabase = createServerSupabase();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: 'Non authentifié' }, { status: 401 });
  const { data: session } = await supabase.from('sessions').select('*').eq('id', params.id).eq('user_id', user.id).single();
  if (!session) return NextResponse.json({ error: 'Session introuvable' }, { status: 404 });

  const { provider } = await request.json();
  if (!provider || !['netlify', 'vercel', 'cloudflare'].includes(provider)) {
    return NextResponse.json({ error: 'Provider invalide' }, { status: 400 });
  }

  const tokens = await getUserTokens(user.id);
  if (!tokens) return NextResponse.json({ error: 'Tokens non configurés. Allez dans Paramètres.' }, { status: 400 });
  if (!tokens.github_token) return NextResponse.json({ error: 'Token GitHub manquant' }, { status: 400 });

  const { data: files } = await supabase.from('generated_files').select('*').eq('session_id', session.id);
  if (!files || files.length === 0) return NextResponse.json({ error: 'Aucun fichier généré' }, { status: 400 });

  const { data: deployment } = await supabase.from('deployments').insert({ session_id: session.id, status: 'in_progress' }).select().single();

  try {
    const repoName = `prodcoach-app-${Date.now()}`;
    const repoUrl = await createGitHubRepo(repoName, tokens.github_token);
    const repoFullName = repoUrl.replace('https://github.com/', '').replace('.git', '');
    await pushFilesToRepo(repoFullName, files.map(f => ({ path: f.file_path, content: f.content })), tokens.github_token);

    let supabaseProjectRef = '';
    if (tokens.supabase_management_token) {
      const dbPassword = 'Temp' + Math.random().toString(36).slice(-8);
      const supabaseProject = await createSupabaseProject(repoName, dbPassword, tokens.supabase_management_token);
      supabaseProjectRef = supabaseProject.id;
      const sql = `create table if not exists items ( id bigint generated by default as identity primary key, name text, created_at timestamptz default now() );`;
      await executeSqlOnProject(supabaseProjectRef, sql, tokens.supabase_management_token);
    }

    let deployResult;
    if (provider === 'netlify') {
      if (!tokens.netlify_access_token) throw new Error('Token Netlify manquant');
      deployResult = await deployToNetlify(tokens.netlify_access_token, repoFullName, repoName);
    } else if (provider === 'vercel') {
      if (!tokens.vercel_access_token) throw new Error('Token Vercel manquant');
      deployResult = await deployToVercel(tokens.vercel_access_token, repoUrl, repoName);
    } else if (provider === 'cloudflare') {
      if (!tokens.cloudflare_api_token || !tokens.cloudflare_account_id) throw new Error('Token Cloudflare ou Account ID manquant');
      deployResult = await deployToCloudflare(tokens.cloudflare_api_token, tokens.cloudflare_account_id, repoUrl, repoName);
    }

    await supabase.from('deployments').update({
      status: 'success',
      github_repo_url: repoUrl,
      supabase_project_ref: supabaseProjectRef || null,
      logs: `Déployé sur ${provider}: ${deployResult!.url}`,
    }).eq('id', deployment!.id);

    return NextResponse.json({ deployment: deployment!.id, repoUrl, deployUrl: deployResult!.url });
  } catch (err: any) {
    await supabase.from('deployments').update({ status: 'failed', logs: err.message }).eq('id', deployment!.id);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
